"""add_backtest_batches_and_batch_id

Revision ID: 216897ee6c5a
Revises: 29535fedaf94
Create Date: 2026-04-18 02:40:52.759107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216897ee6c5a'
down_revision: Union[str, None] = '29535fedaf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbols_json', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_batches_status'), 'backtest_batches', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_batches_user_id'), 'backtest_batches', ['user_id'], unique=False)
    op.add_column('backtest_runs', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_backtest_runs_batch_id'), 'backtest_runs', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'backtest_runs', 'backtest_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backtest_runs', type_='foreignkey')
    op.drop_index(op.f('ix_backtest_runs_batch_id'), table_name='backtest_runs')
    op.drop_column('backtest_runs', 'batch_id')
    op.drop_index(op.f('ix_backtest_batches_user_id'), table_name='backtest_batches')
    op.drop_index(op.f('ix_backtest_batches_status'), table_name='backtest_batches')
    op.drop_table('backtest_batches')
    # ### end Alembic commands ###
